"""Build exercise library JSON from standard strength & conditioning texts.
Based on: NSCA CSCS, NASM CPT, ACE, 基础肌动学, 体能训练, 功能性动作科学
"""
import json

EXERCISES = [
    # ===== SQUAT PATTERNS (蹲) =====
    {
        "id": "ex-001",
        "name_zh": "杠铃深蹲",
        "name_en": "Barbell Back Squat",
        "category": "杠铃主项",
        "primary_muscles": ["股四头肌", "臀大肌"],
        "secondary_muscles": ["腘绳肌", "竖脊肌", "核心肌群", "内收肌群"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "杠铃，深蹲架",
        "contraindications": ["腰椎间盘突出急性期", "严重膝关节炎", "未控制的血压过高"],
        "alternatives": ["ex-002", "ex-004", "ex-005"],
        "common_errors": ["膝内扣", "脚跟离地", "过度前倾", "深度不足"],
        "progression_rules": "先自重→高脚杯深蹲→前蹲→后蹲。股骨低于水平面但不过度。加负荷前需动作稳定。"
    },
    {
        "id": "ex-002",
        "name_zh": "高脚杯深蹲",
        "name_en": "Goblet Squat",
        "category": "哑铃",
        "primary_muscles": ["股四头肌", "臀大肌"],
        "secondary_muscles": ["核心肌群", "上背部"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "哑铃或壶铃",
        "contraindications": ["急性膝痛", "严重平衡障碍"],
        "alternatives": ["ex-005", "ex-004"],
        "common_errors": ["膝内扣", "圆背", "重心偏移"],
        "progression_rules": "自重→轻负荷高脚杯→杠铃深蹲。重点在前链激活和躯干直立。"
    },
    {
        "id": "ex-003",
        "name_zh": "杠铃前蹲",
        "name_en": "Barbell Front Squat",
        "category": "杠铃主项",
        "primary_muscles": ["股四头肌", "臀大肌"],
        "secondary_muscles": ["核心肌群", "上背部", "腘绳肌"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "高级",
        "equipment": "杠铃",
        "contraindications": ["腕关节活动度严重受限", "肩关节撞击症"],
        "alternatives": ["ex-001"],
        "common_errors": ["肘下沉", "上背圆屈", "膝内扣"],
        "progression_rules": "后蹲技术扎实后引入。需要良好腕/肩活动度。"
    },
    {
        "id": "ex-004",
        "name_zh": "保加利亚分腿蹲",
        "name_en": "Bulgarian Split Squat",
        "category": "哑铃",
        "primary_muscles": ["股四头肌", "臀大肌"],
        "secondary_muscles": ["腘绳肌", "核心肌群", "髋屈肌拉伸"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "哑铃，训练凳",
        "contraindications": ["膝关节严重不稳", "平衡严重障碍"],
        "alternatives": ["ex-006", "ex-002"],
        "common_errors": ["前膝超过脚尖过多", "后腿过高", "骨盆倾斜"],
        "progression_rules": "自重→轻负荷。单侧稳定性训练的重要进阶。"
    },
    {
        "id": "ex-005",
        "name_zh": "自重深蹲",
        "name_en": "Bodyweight Squat",
        "category": "自重",
        "primary_muscles": ["股四头肌", "臀大肌"],
        "secondary_muscles": ["核心肌群", "腘绳肌"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "无",
        "contraindications": ["急性膝关节损伤"],
        "alternatives": [],
        "common_errors": ["膝内扣", "脚跟离地", "弓背"],
        "progression_rules": "所有蹲类动作基础。FMS深蹲筛查过关后再进阶。"
    },
    {
        "id": "ex-006",
        "name_zh": "弓步蹲",
        "name_en": "Lunge",
        "category": "自重",
        "primary_muscles": ["股四头肌", "臀大肌"],
        "secondary_muscles": ["腘绳肌", "核心肌群", "小腿三头肌"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "哑铃（可选）",
        "contraindications": ["严重膝关节炎", "平衡严重障碍"],
        "alternatives": ["ex-005", "ex-004"],
        "common_errors": ["前膝内扣", "躯干侧倾", "步幅过小"],
        "progression_rules": "自重→负重弓步→行走弓步→多平面弓步。"
    },
    # ===== HIP HINGE (铰链) =====
    {
        "id": "ex-007",
        "name_zh": "杠铃硬拉",
        "name_en": "Barbell Deadlift",
        "category": "杠铃主项",
        "primary_muscles": ["腘绳肌", "臀大肌", "竖脊肌"],
        "secondary_muscles": ["背阔肌", "斜方肌", "核心肌群", "前臂"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "杠铃",
        "contraindications": ["腰椎间盘突出", "急性下背痛", "未控制的血压过高"],
        "alternatives": ["ex-008", "ex-009", "ex-010"],
        "common_errors": ["圆背", "杠铃远离身体", "髋上升过快", "过度伸腰"],
        "progression_rules": "需先掌握髋铰链模式。从六角杠硬拉或架上硬拉入门。"
    },
    {
        "id": "ex-008",
        "name_zh": "六角杠硬拉",
        "name_en": "Trap Bar Deadlift",
        "category": "杠铃主项",
        "primary_muscles": ["腘绳肌", "臀大肌", "股四头肌"],
        "secondary_muscles": ["竖脊肌", "核心肌群", "上背部"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "六角杠铃",
        "contraindications": ["急性腰椎间盘突出"],
        "alternatives": ["ex-007", "ex-009"],
        "common_errors": ["圆背", "重心偏前", "膝过多参与"],
        "progression_rules": "硬拉初学者首选。中心负荷，对腰椎压力小。"
    },
    {
        "id": "ex-009",
        "name_zh": "壶铃摆举",
        "name_en": "Kettlebell Swing",
        "category": "其他",
        "primary_muscles": ["臀大肌", "腘绳肌"],
        "secondary_muscles": ["核心肌群", "竖脊肌", "肩部"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "壶铃",
        "contraindications": ["急性下背痛", "肩关节撞击症"],
        "alternatives": ["ex-008"],
        "common_errors": ["用臂甩而非髋驱动", "圆背", "过度下蹲"],
        "progression_rules": "先掌握髋铰链→硬拉→再学壶铃摆举。"
    },
    {
        "id": "ex-010",
        "name_zh": "罗马尼亚硬拉",
        "name_en": "Romanian Deadlift (RDL)",
        "category": "杠铃主项",
        "primary_muscles": ["腘绳肌", "臀大肌"],
        "secondary_muscles": ["竖脊肌", "核心肌群"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "杠铃或哑铃",
        "contraindications": ["急性腰椎间盘突出"],
        "alternatives": ["ex-008"],
        "common_errors": ["圆背", "膝锁死", "过度超伸"],
        "progression_rules": "侧重腘绳肌离心控制。膝微屈，髋后移，杠铃沿腿下放。"
    },
    # ===== HORIZONTAL PRESS (水平推) =====
    {
        "id": "ex-011",
        "name_zh": "杠铃卧推",
        "name_en": "Barbell Bench Press",
        "category": "杠铃主项",
        "primary_muscles": ["胸大肌", "三角肌前束", "肱三头肌"],
        "secondary_muscles": ["前锯肌", "核心肌群"],
        "joint_action": "推",
        "movement_plane": "水平面",
        "difficulty": "中级",
        "equipment": "杠铃，卧推架",
        "contraindications": ["肩关节脱位史", "严重肩袖损伤", "胸肋关节炎急性期"],
        "alternatives": ["ex-012", "ex-013"],
        "common_errors": ["肩胛不稳定", "弹胸", "臀部离凳", "握距过宽"],
        "progression_rules": "先掌握俯卧撑→哑铃卧推→杠铃卧推。有保护者时必须。"
    },
    {
        "id": "ex-012",
        "name_zh": "哑铃卧推",
        "name_en": "Dumbbell Bench Press",
        "category": "哑铃",
        "primary_muscles": ["胸大肌", "三角肌前束", "肱三头肌"],
        "secondary_muscles": ["前锯肌", "核心肌群"],
        "joint_action": "推",
        "movement_plane": "水平面",
        "difficulty": "初级",
        "equipment": "哑铃，训练凳",
        "contraindications": ["急性肩袖损伤"],
        "alternatives": ["ex-011", "ex-014", "ex-015"],
        "common_errors": ["肩胛骨前伸", "肘过度外展", "两侧不平衡"],
        "progression_rules": "肩关节友好的卧推变式。从轻重量开始感受胸肌收缩。"
    },
    {
        "id": "ex-013",
        "name_zh": "俯卧撑",
        "name_en": "Push-Up",
        "category": "自重",
        "primary_muscles": ["胸大肌", "三角肌前束", "肱三头肌"],
        "secondary_muscles": ["前锯肌", "核心肌群"],
        "joint_action": "推",
        "movement_plane": "水平面",
        "difficulty": "初级",
        "equipment": "无",
        "contraindications": ["腕管综合征急性期", "严重肩关节撞击"],
        "alternatives": ["ex-015"],
        "common_errors": ["塌腰", "肘过度外展（翼状）", "半程动作"],
        "progression_rules": "上斜→平卧→下斜。可进阶为爆发性俯卧撑。"
    },
    {
        "id": "ex-014",
        "name_zh": "哑铃飞鸟",
        "name_en": "Dumbbell Fly",
        "category": "哑铃",
        "primary_muscles": ["胸大肌"],
        "secondary_muscles": ["三角肌前束", "肱二头肌"],
        "joint_action": "推",
        "movement_plane": "水平面",
        "difficulty": "中级",
        "equipment": "哑铃，训练凳",
        "contraindications": ["肩关节前不稳定"],
        "alternatives": ["ex-016"],
        "common_errors": ["肘下沉过深", "重量过大导致肩关节应力", "肩胛骨不稳定"],
        "progression_rules": "孤立胸肌动作。在基础推类动作后进行。轻重量高次数。"
    },
    {
        "id": "ex-015",
        "name_zh": "跪姿俯卧撑",
        "name_en": "Knee Push-Up",
        "category": "自重",
        "primary_muscles": ["胸大肌", "三角肌前束"],
        "secondary_muscles": ["肱三头肌", "核心肌群"],
        "joint_action": "推",
        "movement_plane": "水平面",
        "difficulty": "初级",
        "equipment": "无",
        "contraindications": ["腕管综合征急性期"],
        "alternatives": ["ex-013"],
        "common_errors": ["塌腰", "颈前伸"],
        "progression_rules": "俯卧撑入门变式。能做10次以上转为标准俯卧撑。"
    },
    # ===== VERTICAL PRESS (垂直推) =====
    {
        "id": "ex-016",
        "name_zh": "杠铃推举（站姿肩推）",
        "name_en": "Barbell Overhead Press (Standing)",
        "category": "杠铃主项",
        "primary_muscles": ["三角肌前束", "三角肌中束"],
        "secondary_muscles": ["肱三头肌", "上斜方肌", "核心肌群"],
        "joint_action": "推",
        "movement_plane": "矢状面",
        "difficulty": "高级",
        "equipment": "杠铃",
        "contraindications": ["肩峰撞击症", "颈椎病", "高血压未控制"],
        "alternatives": ["ex-017", "ex-018"],
        "common_errors": ["过度伸腰（肋骨外翻）", "杠铃轨迹不直", "握距过宽"],
        "progression_rules": "哑铃推举→杠铃推举。核心稳定是先决条件。"
    },
    {
        "id": "ex-017",
        "name_zh": "哑铃推举",
        "name_en": "Dumbbell Shoulder Press",
        "category": "哑铃",
        "primary_muscles": ["三角肌前束", "三角肌中束"],
        "secondary_muscles": ["肱三头肌", "上斜方肌"],
        "joint_action": "推",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "哑铃",
        "contraindications": ["急性肩袖损伤"],
        "alternatives": ["ex-016", "ex-018"],
        "common_errors": ["肩关节上提过多", "两侧不平衡", "腕关节弯曲"],
        "progression_rules": "肩推入门首选。手腕中立位，避免翼状肩。"
    },
    {
        "id": "ex-018",
        "name_zh": "侧平举",
        "name_en": "Lateral Raise",
        "category": "哑铃",
        "primary_muscles": ["三角肌中束"],
        "secondary_muscles": ["三角肌前束", "斜方肌"],
        "joint_action": "推",
        "movement_plane": "冠状面",
        "difficulty": "初级",
        "equipment": "哑铃",
        "contraindications": ["肩峰下撞击症"],
        "alternatives": ["ex-019"],
        "common_errors": ["使用爆发力摆动", "肩关节上提代替外展", "过重"],
        "progression_rules": "轻重量（2-5kg开始），高次数（12-15），注重控制。"
    },
    {
        "id": "ex-019",
        "name_zh": "绳索侧平举",
        "name_en": "Cable Lateral Raise",
        "category": "绳索",
        "primary_muscles": ["三角肌中束"],
        "secondary_muscles": ["三角肌后束"],
        "joint_action": "推",
        "movement_plane": "冠状面",
        "difficulty": "初级",
        "equipment": "龙门架",
        "contraindications": ["肩峰下撞击症"],
        "alternatives": ["ex-018"],
        "common_errors": ["身体摆动", "肘低于腕"],
        "progression_rules": "绳索提供恒定张力，比哑铃更适合感受肩中束。"
    },
    # ===== HORIZONTAL PULL (水平拉) =====
    {
        "id": "ex-020",
        "name_zh": "杠铃划船",
        "name_en": "Barbell Row",
        "category": "杠铃主项",
        "primary_muscles": ["背阔肌", "斜方肌中下束", "菱形肌"],
        "secondary_muscles": ["竖脊肌", "肱二头肌", "三角肌后束", "核心肌群"],
        "joint_action": "拉",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "杠铃",
        "contraindications": ["急性腰椎间盘突出"],
        "alternatives": ["ex-021", "ex-022"],
        "common_errors": ["圆背（下背危险）", "身体摆动过大", "肘外展不足"],
        "progression_rules": "先掌握髋铰链稳定→哑铃划船→杠铃划船。"
    },
    {
        "id": "ex-021",
        "name_zh": "单臂哑铃划船",
        "name_en": "One-Arm Dumbbell Row",
        "category": "哑铃",
        "primary_muscles": ["背阔肌", "菱形肌"],
        "secondary_muscles": ["肱二头肌", "三角肌后束"],
        "joint_action": "拉",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "哑铃，训练凳",
        "contraindications": [],
        "alternatives": ["ex-020", "ex-022"],
        "common_errors": ["躯干旋转", "肘外展不充分", "耸肩代偿"],
        "progression_rules": "背部训练入门首选单侧动作。对腰椎友好。"
    },
    {
        "id": "ex-022",
        "name_zh": "坐姿绳索划船",
        "name_en": "Seated Cable Row",
        "category": "绳索",
        "primary_muscles": ["背阔肌", "菱形肌", "斜方肌中下束"],
        "secondary_muscles": ["肱二头肌", "三角肌后束", "竖脊肌"],
        "joint_action": "拉",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "龙门架",
        "contraindications": [],
        "alternatives": ["ex-020", "ex-021"],
        "common_errors": ["过度伸腰", "膝盖锁死", "耸肩"],
        "progression_rules": "恒定张力，适合肌肉感受。变化握距/握法（宽/窄/V把）。"
    },
    {
        "id": "ex-023",
        "name_zh": "面拉",
        "name_en": "Face Pull",
        "category": "绳索",
        "primary_muscles": ["三角肌后束", "斜方肌中下束", "肩外旋肌群"],
        "secondary_muscles": ["菱形肌"],
        "joint_action": "拉",
        "movement_plane": "水平面",
        "difficulty": "初级",
        "equipment": "龙门架 + 绳索",
        "contraindications": ["严重肩关节不稳"],
        "alternatives": ["ex-024"],
        "common_errors": ["重量过大导致借力", "外旋不足", "肘低于肩"],
        "progression_rules": "纠正性/预康复核心动作。轻重量，高次数（15-20），注重外旋。"
    },
    {
        "id": "ex-024",
        "name_zh": "反向蝴蝶机",
        "name_en": "Reverse Pec Deck",
        "category": "固定器械",
        "primary_muscles": ["三角肌后束"],
        "secondary_muscles": ["菱形肌", "斜方肌中下束"],
        "joint_action": "拉",
        "movement_plane": "水平面",
        "difficulty": "初级",
        "equipment": "蝴蝶机",
        "contraindications": ["严重肩关节前不稳定"],
        "alternatives": ["ex-023"],
        "common_errors": ["肩胛前伸", "重量过大", "动作幅度不足"],
        "progression_rules": "孤立后束。训练课中放在推类动作后以保持前后平衡。"
    },
    # ===== VERTICAL PULL (垂直拉) =====
    {
        "id": "ex-025",
        "name_zh": "引体向上",
        "name_en": "Pull-Up / Chin-Up",
        "category": "自重",
        "primary_muscles": ["背阔肌", "肱二头肌"],
        "secondary_muscles": ["斜方肌中下束", "菱形肌", "核心肌群"],
        "joint_action": "拉",
        "movement_plane": "冠状面",
        "difficulty": "高级",
        "equipment": "单杠",
        "contraindications": ["急性肩袖损伤", "肩关节脱位史"],
        "alternatives": ["ex-026", "ex-027"],
        "common_errors": ["半程范围", "摆动借力", "过度反弓"],
        "progression_rules": "弹力带辅助→反向划船→等长悬挂→标准引体。正手（pull-up）难度>反手（chin-up）。"
    },
    {
        "id": "ex-026",
        "name_zh": "高位下拉",
        "name_en": "Lat Pulldown",
        "category": "固定器械",
        "primary_muscles": ["背阔肌"],
        "secondary_muscles": ["肱二头肌", "菱形肌", "三角肌后束"],
        "joint_action": "拉",
        "movement_plane": "冠状面",
        "difficulty": "初级",
        "equipment": "高位下拉器",
        "contraindications": ["急性肩关节脱位"],
        "alternatives": ["ex-025"],
        "common_errors": ["握距过宽", "身体后仰过度", "下拉至颈后"],
        "progression_rules": "引体向上入门训练。下拉至锁骨水平即可，勿拉到颈后（肩关节风险）。"
    },
    {
        "id": "ex-027",
        "name_zh": "助力引体向上机",
        "name_en": "Assisted Pull-Up Machine",
        "category": "固定器械",
        "primary_muscles": ["背阔肌", "肱二头肌"],
        "secondary_muscles": ["核心肌群"],
        "joint_action": "拉",
        "movement_plane": "冠状面",
        "difficulty": "初级",
        "equipment": "助力引体向上机",
        "contraindications": [],
        "alternatives": ["ex-025", "ex-026"],
        "common_errors": ["过度依赖助力", "不完整动作范围"],
        "progression_rules": "随着力量提升逐步减少助力重量。"
    },
    # ===== CORE (核心) =====
    {
        "id": "ex-028",
        "name_zh": "平板支撑",
        "name_en": "Plank",
        "category": "自重",
        "primary_muscles": ["腹横肌", "腹直肌", "核心肌群"],
        "secondary_muscles": ["竖脊肌", "肩部稳定肌"],
        "joint_action": "旋转",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "无",
        "contraindications": ["急性腰椎间盘突出（做短时改良版）"],
        "alternatives": ["ex-029", "ex-030"],
        "common_errors": ["塌腰", "臀过高", "颈前伸"],
        "progression_rules": "跪姿→标准→单腿→不稳定面→负重。FMS躯干稳定性筛查通过后再进阶。"
    },
    {
        "id": "ex-029",
        "name_zh": "鸟狗式",
        "name_en": "Bird Dog",
        "category": "自重",
        "primary_muscles": ["竖脊肌", "腹横肌", "臀大肌"],
        "secondary_muscles": ["肩部稳定肌", "核心肌群"],
        "joint_action": "旋转",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "无",
        "contraindications": [],
        "alternatives": ["ex-028"],
        "common_errors": ["骨盆旋转", "肩/髋过高", "快速抖动"],
        "progression_rules": "下背康复/预康复必做。追求控制而非速度/幅度。"
    },
    {
        "id": "ex-030",
        "name_zh": "死虫式",
        "name_en": "Dead Bug",
        "category": "自重",
        "primary_muscles": ["腹横肌", "腹直肌"],
        "secondary_muscles": ["盆底肌"],
        "joint_action": "旋转",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "无",
        "contraindications": [],
        "alternatives": ["ex-028"],
        "common_errors": ["下背离地", "颈紧张", "憋气"],
        "progression_rules": "核心稳定性入门首选。下背始终贴地。先单腿→对侧手腿。"
    },
    # ===== EXPLOSIVE/POWER (爆发力) =====
    {
        "id": "ex-031",
        "name_zh": "高翻",
        "name_en": "Power Clean",
        "category": "杠铃主项",
        "primary_muscles": ["臀大肌", "腘绳肌", "竖脊肌", "股四头肌"],
        "secondary_muscles": ["斜方肌", "三角肌", "核心肌群"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "高级",
        "equipment": "杠铃，举重台",
        "contraindications": ["腕关节活动度严重受限（前架位）", "肩/肘/腰椎急性损伤"],
        "alternatives": ["ex-032", "ex-033"],
        "common_errors": ["过早拉臂", "杠铃轨迹不直", "接杠不稳"],
        "progression_rules": "先颈后推举→悬垂高翻→膝上高翻→完整高翻。需专业教练指导。"
    },
    {
        "id": "ex-032",
        "name_zh": "哑铃抓举",
        "name_en": "Dumbbell Snatch",
        "category": "哑铃",
        "primary_muscles": ["臀大肌", "腘绳肌", "三角肌", "斜方肌"],
        "secondary_muscles": ["核心肌群", "前臂"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "哑铃",
        "contraindications": ["肩关节不稳", "急性肘关节痛"],
        "alternatives": ["ex-031", "ex-033"],
        "common_errors": ["发力时机不对", "侧向偏移"],
        "progression_rules": "单臂→交替→双臂。相比杠铃变式技术要求低但爆发力效果好。"
    },
    {
        "id": "ex-033",
        "name_zh": "跳箱",
        "name_en": "Box Jump",
        "category": "自重",
        "primary_muscles": ["股四头肌", "臀大肌", "腓肠肌"],
        "secondary_muscles": ["核心肌群", "腘绳肌"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "跳箱",
        "contraindications": ["急性膝/踝损伤", "跟腱炎"],
        "alternatives": ["ex-034"],
        "common_errors": ["箱高过高", "落地不稳", "着地后跳下"],
        "progression_rules": "先自重反向跳→低箱→中箱。落地技术>箱高。着地后步下，勿跳下。"
    },
    # ===== LOWER BODY ACCESSORIES (下肢辅助) =====
    {
        "id": "ex-034",
        "name_zh": "腿举",
        "name_en": "Leg Press",
        "category": "固定器械",
        "primary_muscles": ["股四头肌"],
        "secondary_muscles": ["臀大肌", "腘绳肌"],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "腿举机",
        "contraindications": ["严重高血压", "膝关节过度屈曲痛"],
        "alternatives": ["ex-005", "ex-001"],
        "common_errors": ["深度过大（骨盆翻转）", "膝锁死", "脚位过高"],
        "progression_rules": "膝关节角度不超过90°。下背全程贴垫。"
    },
    {
        "id": "ex-035",
        "name_zh": "腿弯举",
        "name_en": "Leg Curl",
        "category": "固定器械",
        "primary_muscles": ["腘绳肌"],
        "secondary_muscles": ["腓肠肌"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "腿弯举机",
        "contraindications": ["急性腘绳肌拉伤"],
        "alternatives": ["ex-010"],
        "common_errors": ["骨盆抬起", "爆发力收缩", "不完全伸展"],
        "progression_rules": "高次数（12-15）感受后链。配合直腿硬拉构建完整后链。"
    },
    {
        "id": "ex-036",
        "name_zh": "腿伸展",
        "name_en": "Leg Extension",
        "category": "固定器械",
        "primary_muscles": ["股四头肌"],
        "secondary_muscles": [],
        "joint_action": "蹲",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "腿伸展机",
        "contraindications": ["ACL术后早期（需限ROM）", "髌骨软化症"],
        "alternatives": ["ex-034"],
        "common_errors": ["爆发力伸展", "过度超伸", "趾屈不够"],
        "progression_rules": "孤立股四头肌。深蹲后补充。控制节奏（2-1-2）。"
    },
    # ===== UPPER BODY ACCESSORIES (上肢辅助) =====
    {
        "id": "ex-037",
        "name_zh": "肱二头肌弯举",
        "name_en": "Bicep Curl",
        "category": "哑铃",
        "primary_muscles": ["肱二头肌"],
        "secondary_muscles": ["肱肌", "肱桡肌"],
        "joint_action": "拉",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "哑铃或杠铃",
        "contraindications": ["肘关节内侧副韧带损伤"],
        "alternatives": ["ex-038"],
        "common_errors": ["身体摆动借力", "不完全伸展", "腕屈曲"],
        "progression_rules": "单臂交替→双臂→EZ杠→杠铃。加旋转（旋后）以更好激活。"
    },
    {
        "id": "ex-038",
        "name_zh": "三头臂屈伸",
        "name_en": "Tricep Extension / Skull Crusher",
        "category": "哑铃",
        "primary_muscles": ["肱三头肌"],
        "secondary_muscles": ["肘肌"],
        "joint_action": "推",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "哑铃或杠铃或绳索",
        "contraindications": ["肘关节骨刺", "鹰嘴滑囊炎"],
        "alternatives": ["ex-039"],
        "common_errors": ["肘外展", "肩关节不稳定", "不完全伸展"],
        "progression_rules": "绳索下压→哑铃→杠铃。肘关节上方使用绳索减少关节应力。"
    },
    {
        "id": "ex-039",
        "name_zh": "双杠臂屈伸",
        "name_en": "Dips",
        "category": "自重",
        "primary_muscles": ["肱三头肌", "胸大肌下束"],
        "secondary_muscles": ["三角肌前束"],
        "joint_action": "推",
        "movement_plane": "矢状面",
        "difficulty": "高级",
        "equipment": "双杠",
        "contraindications": ["肩关节前不稳定", "胸锁关节问题", "锁骨骨折史"],
        "alternatives": ["ex-038"],
        "common_errors": ["深度过大（肩超伸）", "肘外展过大", "身体摆动"],
        "progression_rules": "弹力带辅助→辅助机→自重→负重。ROM控制在上臂与地面平行即可。"
    },
    # ===== CORRECTIVE & MOBILITY (纠正性/灵活性) =====
    {
        "id": "ex-040",
        "name_zh": "蛤式开合",
        "name_en": "Clamshell",
        "category": "自重",
        "primary_muscles": ["臀中肌", "髋外旋肌群"],
        "secondary_muscles": [],
        "joint_action": "旋转",
        "movement_plane": "冠状面",
        "difficulty": "初级",
        "equipment": "弹力带（可选）",
        "contraindications": ["急性髋关节痛"],
        "alternatives": [],
        "common_errors": ["骨盆旋转", "快速摆动", "脚离地"],
        "progression_rules": "纠正性训练核心动作。自重→弹力带→侧卧腿外展。膝前痛/ITB综合征首选。"
    },
    {
        "id": "ex-041",
        "name_zh": "臀桥",
        "name_en": "Glute Bridge",
        "category": "自重",
        "primary_muscles": ["臀大肌"],
        "secondary_muscles": ["腘绳肌", "核心肌群"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "无",
        "contraindications": [],
        "alternatives": ["ex-007"],
        "common_errors": ["用腰代偿而非臀", "臀未充分收缩", "下巴上扬"],
        "progression_rules": "双脚→单脚→负重→不稳定面。下背痛康复入门必做。"
    },
    {
        "id": "ex-042",
        "name_zh": "肩袖外旋",
        "name_en": "External Rotation (Rotator Cuff)",
        "category": "绳索",
        "primary_muscles": ["冈下肌", "小圆肌"],
        "secondary_muscles": ["三角肌后束"],
        "joint_action": "旋转",
        "movement_plane": "水平面",
        "difficulty": "初级",
        "equipment": "弹力带或绳索或小哑铃",
        "contraindications": ["急性肩袖全层撕裂"],
        "alternatives": ["ex-023"],
        "common_errors": ["肘离开身体", "耸肩", "使用过大重量"],
        "progression_rules": "预康复/纠正性训练。在所有上肢推类训练前做2-3组15次。"
    },
    # ===== ENDURANCE / CONDITIONING (耐力/体能) =====
    {
        "id": "ex-043",
        "name_zh": "波比跳",
        "name_en": "Burpee",
        "category": "自重",
        "primary_muscles": ["全身综合"],
        "secondary_muscles": ["心肺系统"],
        "joint_action": "推",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "无",
        "contraindications": ["严重心血管疾病", "急性关节损伤"],
        "alternatives": ["ex-044"],
        "common_errors": ["跳高不足", "俯卧阶段塌腰", "节奏太快失去控制"],
        "progression_rules": "无跳跃版→标准→高跳版。HIIT/Tabata核心动作。"
    },
    {
        "id": "ex-044",
        "name_zh": "壶铃摆举（双摆）",
        "name_en": "Kettlebell Double Swing",
        "category": "其他",
        "primary_muscles": ["臀大肌", "腘绳肌", "心肺系统"],
        "secondary_muscles": ["核心肌群", "前臂", "肩部"],
        "joint_action": "铰链",
        "movement_plane": "矢状面",
        "difficulty": "中级",
        "equipment": "壶铃",
        "contraindications": ["急性下背痛"],
        "alternatives": ["ex-009"],
        "common_errors": ["用臂而非髋", "下背弯曲", "手臂过度用力"],
        "progression_rules": "单壶铃→双壶铃。髋爆发力驱动，手臂仅传递力量。"
    },
    {
        "id": "ex-045",
        "name_zh": "农夫行走",
        "name_en": "Farmer's Walk",
        "category": "其他",
        "primary_muscles": ["核心肌群", "前臂", "斜方肌"],
        "secondary_muscles": ["臀大肌", "股四头肌"],
        "joint_action": "提",
        "movement_plane": "矢状面",
        "difficulty": "初级",
        "equipment": "哑铃或壶铃或农夫杠",
        "contraindications": ["严重脊柱侧弯", "急性肩关节损伤"],
        "alternatives": [],
        "common_errors": ["耸肩", "步伐不稳", "单侧承重不均"],
        "progression_rules": "轻→重，短距离→长距离。核心/握力/体态综合训练。"
    },
]

output = {
    "_description": "动作库 - 来自 NSCA CSCS, NASM CPT, ACE, 基础肌动学, 体能训练, 功能性动作科学",
    "_source": "NSCA CSCS 5th, NASM CPT 7th, ACE, 基础肌动学, 功能性动作科学（FMS）",
    "_note": (
        "动作分类: 蹲/铰链/推/拉/旋转/提。"
        "difficulty: 初级(初学者适用)/中级(有一定训练基础)/高级(需专业指导)。"
        "progression_rules指示从最易变式到完整动作的进阶。"
    ),
    "_fields": {
        "id": "动作唯一标识",
        "name_zh": "中文名称",
        "name_en": "英文名称（如有）",
        "category": "杠铃主项/哑铃/固定器械/绳索/自重/其他",
        "primary_muscles": ["主要目标肌群"],
        "secondary_muscles": ["辅助肌群"],
        "joint_action": "关节运动类型（推/拉/蹲/铰链/提/旋转）",
        "movement_plane": "运动面（矢状面/冠状面/水平面）",
        "difficulty": "初级/中级/高级",
        "equipment": "所需器械",
        "contraindications": ["禁忌症"],
        "alternatives": ["替代动作ID"],
        "common_errors": ["常见错误"],
        "progression_rules": "加重/进阶规则"
    },
    "exercises": EXERCISES
}

outpath = r"D:\04_claude_code\01_Fitness\fitness-advisor\assets\exercise-library.json"
with open(outpath, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Written {len(EXERCISES)} exercises to {outpath}")
print(f"File size: {__import__('os').path.getsize(outpath) / 1024:.0f} KB")
